//Class for adding item in the billing summary
package rohanbakery;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


public class addItem extends javax.swing.JFrame {

    //Global variables of the class
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    boolean listLoaded = false;
    
    //Constructor for initialist components
    public addItem() {
        initComponents();
        centerFrame();  //Set frame in the center of the screen
        conn = ConnectToDatabase.getConnection();   //Get connection to the database
        setComboBoxValues();    //Set the combo box values
        listLoaded = true;  //List has been loaded completely
    }
    
    //Functin to set frame in the center of the screen
    public void centerFrame() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation((size.width/2 - getWidth()/2),(size.height/2 - getHeight()/2));
    }
    
    //Function to set the values of the combo box using the item names in the items table
    public void setComboBoxValues() {
        String sql = "select iName from item where iActive=? order by iName asc";
        
        cbo_iName.removeAllItems();
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1,"Yes");
            rs = pst.executeQuery();
            
            while (rs.next()) {
                cbo_iName.addItem(rs.getString(1));
            }
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Item list cannot be loaded");
        }finally {
            try{
                rs.close();
                pst.close();
                
            }catch(Exception e) {}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_bNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbo_iName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_bCustName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_bQty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_iId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_iSp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_bAmount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_iCp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_calcAmount = new javax.swing.JButton();
        btn_clearitem = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_bDate = new org.jdesktop.swingx.JXDatePicker();
        btn_clearAll = new javax.swing.JButton();
        scrollPane_iDescription = new javax.swing.JScrollPane();
        txt_iDescription = new javax.swing.JTextArea();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add item to billing");
        setResizable(false);

        pnl_main.setLayout(null);

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        pnl_main.add(btn_back);
        btn_back.setBounds(660, 10, 110, 30);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Add item to billing :");
        pnl_main.add(jLabel1);
        jLabel1.setBounds(30, 10, 170, 23);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Bill number : ");
        pnl_main.add(jLabel2);
        jLabel2.setBounds(30, 60, 110, 16);

        txt_bNumber.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_bNumber);
        txt_bNumber.setBounds(140, 50, 210, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Bill date : ");
        pnl_main.add(jLabel3);
        jLabel3.setBounds(30, 110, 110, 16);

        cbo_iName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbo_iName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_iNameItemStateChanged(evt);
            }
        });
        pnl_main.add(cbo_iName);
        cbo_iName.setBounds(140, 200, 210, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Customer name : ");
        pnl_main.add(jLabel4);
        jLabel4.setBounds(30, 160, 110, 16);

        txt_bCustName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_bCustName);
        txt_bCustName.setBounds(140, 150, 210, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Item name : ");
        pnl_main.add(jLabel5);
        jLabel5.setBounds(30, 210, 110, 16);

        txt_bQty.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_bQty);
        txt_bQty.setBounds(560, 50, 210, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Item quantity : ");
        pnl_main.add(jLabel7);
        jLabel7.setBounds(450, 60, 120, 16);

        txt_iId.setEditable(false);
        txt_iId.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_iId);
        txt_iId.setBounds(140, 250, 210, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setText("Selling price : ");
        pnl_main.add(jLabel9);
        jLabel9.setBounds(450, 110, 120, 16);

        txt_iSp.setEditable(false);
        txt_iSp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_iSp);
        txt_iSp.setBounds(560, 100, 210, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setText("Item Id :");
        pnl_main.add(jLabel8);
        jLabel8.setBounds(30, 260, 120, 16);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setText("Item amount : ");
        pnl_main.add(jLabel10);
        jLabel10.setBounds(450, 210, 120, 16);

        txt_bAmount.setEditable(false);
        txt_bAmount.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_bAmount);
        txt_bAmount.setBounds(560, 200, 210, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setText("Cost price : ");
        pnl_main.add(jLabel11);
        jLabel11.setBounds(450, 160, 120, 16);

        txt_iCp.setEditable(false);
        txt_iCp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_iCp);
        txt_iCp.setBounds(560, 150, 210, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setText("Item Description :");
        pnl_main.add(jLabel12);
        jLabel12.setBounds(30, 310, 110, 16);

        btn_calcAmount.setText("Calculate amount");
        btn_calcAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcAmountActionPerformed(evt);
            }
        });
        pnl_main.add(btn_calcAmount);
        btn_calcAmount.setBounds(570, 300, 130, 40);

        btn_clearitem.setText("Clear item details");
        btn_clearitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearitemActionPerformed(evt);
            }
        });
        pnl_main.add(btn_clearitem);
        btn_clearitem.setBounds(420, 350, 130, 40);

        btn_save.setText("Save item");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        pnl_main.add(btn_save);
        btn_save.setBounds(420, 300, 100, 40);
        pnl_main.add(txt_bDate);
        txt_bDate.setBounds(140, 100, 210, 30);

        btn_clearAll.setText("Clear all details");
        btn_clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearAllActionPerformed(evt);
            }
        });
        pnl_main.add(btn_clearAll);
        btn_clearAll.setBounds(570, 350, 130, 40);

        txt_iDescription.setEditable(false);
        txt_iDescription.setColumns(20);
        txt_iDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_iDescription.setLineWrap(true);
        txt_iDescription.setRows(5);
        scrollPane_iDescription.setViewportView(txt_iDescription);

        pnl_main.add(scrollPane_iDescription);
        scrollPane_iDescription.setBounds(140, 300, 210, 130);

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/Background image.jpeg"))); // NOI18N
        pnl_main.add(lbl_background);
        lbl_background.setBounds(0, 0, 820, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Action when any item is selected in the combo box.
    //It displays the item details along with the cost and selling price
    private void cbo_iNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_iNameItemStateChanged
        if(listLoaded) {
            String sql = "select * from item where iName=?";
        
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1,cbo_iName.getSelectedItem().toString());
                rs = pst.executeQuery();
                rs.next();  //Move resultset to the first pointer

                txt_iId.setText(rs.getString(1));
                txt_iDescription.setText(rs.getString(3));
                txt_iCp.setText(rs.getString(5));
                txt_iSp.setText(rs.getString(6));

            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Item details cannot be found");
            }finally {
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e) {}
            }
        }
    }//GEN-LAST:event_cbo_iNameItemStateChanged
    
    //Action performed when calculate amount button is clicked
    private void btn_calcAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcAmountActionPerformed
        int sp, qty, amount;
        sp = Integer.parseInt(txt_iSp.getText());
        qty = Integer.parseInt(txt_bQty.getText());
        amount = sp*qty;
        
        String amt = Integer.toString(amount);
        txt_bAmount.setText(amt);
    }//GEN-LAST:event_btn_calcAmountActionPerformed

    //Action performed to save the item in the billing list
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if((txt_iId.getText()).equals("")) {    //Check to see if bill number is entered
            JOptionPane.showMessageDialog(null,"Please enter the bill number");
        } else {
            String sql ="insert into billing " 
                            + "(bNumber, bDate, bCustName, item_iId, iName, iDescription, bQty, iSp,"
                            + "iCp) values (?,?,?,?,?,?,?,?,?) ";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1,txt_bNumber.getText());
                
                DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                pst.setString(2,format.format(txt_bDate.getDate()));
                
                pst.setString(3,txt_bCustName.getText());
                pst.setInt(4,Integer.parseInt(txt_iId.getText()));
                pst.setString(5,cbo_iName.getSelectedItem().toString());
                pst.setString(6,txt_iDescription.getText());
                pst.setInt(7,Integer.parseInt(txt_bQty.getText()));
                pst.setInt(8,Integer.parseInt(txt_iSp.getText()));
                pst.setInt(9,Integer.parseInt(txt_iCp.getText()));
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Added");

            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }finally {
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e) {}
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed
    
    //Action performed when clear all button is clicked
    private void btn_clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearAllActionPerformed
        
        //Code to remove all selected items
        txt_bNumber.setText("");        
        txt_bDate.setDate(null);
        txt_bCustName.setText("");
        txt_iId.setText("");
        cbo_iName.setSelectedItem(0);
        txt_iDescription.setText("");
        txt_bQty.setText("");
        txt_iSp.setText("");
        txt_iCp.setText("");
        txt_bAmount.setText("");
    }//GEN-LAST:event_btn_clearAllActionPerformed

    //Action performed when only item details need to be cleared
    private void btn_clearitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearitemActionPerformed
        //Code to remove only item detailsdsfsdf
        txt_iId.setText("");
        cbo_iName.setSelectedItem(0);
        txt_iDescription.setText("");
        txt_bQty.setText("");
        txt_iSp.setText("");
        txt_iCp.setText("");
        txt_bAmount.setText("");
    }//GEN-LAST:event_btn_clearitemActionPerformed

    //Code module to go back
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        generateBill gb = new generateBill();
        gb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_calcAmount;
    private javax.swing.JButton btn_clearAll;
    private javax.swing.JButton btn_clearitem;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cbo_iName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JScrollPane scrollPane_iDescription;
    private javax.swing.JTextField txt_bAmount;
    private javax.swing.JTextField txt_bCustName;
    private org.jdesktop.swingx.JXDatePicker txt_bDate;
    private javax.swing.JTextField txt_bNumber;
    private javax.swing.JTextField txt_bQty;
    private javax.swing.JTextField txt_iCp;
    private javax.swing.JTextArea txt_iDescription;
    private javax.swing.JTextField txt_iId;
    private javax.swing.JTextField txt_iSp;
    // End of variables declaration//GEN-END:variables
}
