//Class for adding item in the inventory summary
package rohanbakery;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


public class addInventory extends javax.swing.JFrame {

    //Global variables of the class
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    boolean listLoaded = false;
    
    //Constructor for initialist components
    public addInventory() {
        initComponents();
        centerFrame();  //Set frame in the center of the screen
        conn = ConnectToDatabase.getConnection();   //Get connection to the database
        setComboBoxValues();    //Set the combo box values
        listLoaded = true;  //List has been loaded completely
    }
    
    //Functin to set frame in the center of the screen
    public void centerFrame() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation((size.width/2 - getWidth()/2),(size.height/2 - getHeight()/2));
    }
    
    //Function to set the values of the combo box using the item names in the items table
    public void setComboBoxValues() {
        String sql = "select iName from item where iActive=? order by iName asc";
        
        cbo_iniName.removeAllItems();
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1,"Yes");
            rs = pst.executeQuery();
            
            while (rs.next()) {
                cbo_iniName.addItem(rs.getString(1));
            }
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Item list cannot be loaded");
        }finally {
            try{
                rs.close();
                pst.close();
                
            }catch(Exception e) {}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbo_iniName = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_inQty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_iniId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_clearitem = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        txt_inDate = new org.jdesktop.swingx.JXDatePicker();
        btn_clearAll = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add inventory");
        setAlwaysOnTop(true);
        setResizable(false);

        pnl_main.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Add item to inventory :");
        pnl_main.add(jLabel1);
        jLabel1.setBounds(30, 10, 210, 23);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Inventory date : ");
        pnl_main.add(jLabel3);
        jLabel3.setBounds(30, 60, 110, 16);

        cbo_iniName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbo_iniName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_iniNameItemStateChanged(evt);
            }
        });
        pnl_main.add(cbo_iniName);
        cbo_iniName.setBounds(140, 100, 210, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Select item name : ");
        pnl_main.add(jLabel5);
        jLabel5.setBounds(30, 110, 110, 16);

        txt_inQty.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_inQty);
        txt_inQty.setBounds(140, 200, 210, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Item quantity : ");
        pnl_main.add(jLabel7);
        jLabel7.setBounds(30, 210, 120, 16);

        txt_iniId.setEditable(false);
        txt_iniId.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_iniId);
        txt_iniId.setBounds(140, 150, 210, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setText("Item Id :");
        pnl_main.add(jLabel8);
        jLabel8.setBounds(30, 160, 120, 16);

        btn_clearitem.setText("Clear item details");
        btn_clearitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearitemActionPerformed(evt);
            }
        });
        pnl_main.add(btn_clearitem);
        btn_clearitem.setBounds(190, 290, 130, 40);

        btn_save.setText("Save item");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        pnl_main.add(btn_save);
        btn_save.setBounds(70, 290, 100, 40);

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        pnl_main.add(btn_back);
        btn_back.setBounds(280, 10, 70, 30);
        pnl_main.add(txt_inDate);
        txt_inDate.setBounds(140, 50, 210, 30);

        btn_clearAll.setText("Clear all details");
        btn_clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearAllActionPerformed(evt);
            }
        });
        pnl_main.add(btn_clearAll);
        btn_clearAll.setBounds(130, 350, 130, 40);

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/Background image.jpeg"))); // NOI18N
        pnl_main.add(lbl_background);
        lbl_background.setBounds(0, 0, 400, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Action when any item is selected in the combo box.
    //It displays the item details to be added to the inventory table
    private void cbo_iniNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_iniNameItemStateChanged
        if(listLoaded) {
            String sql = "select * from item where iName=?";
        
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1,cbo_iniName.getSelectedItem().toString());
                rs = pst.executeQuery();
                rs.next();  //Move resultset to the first pointer

                txt_iniId.setText(rs.getString(1));

            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Item details cannot be found");
            }finally {
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e) {}
            }
        }
    }//GEN-LAST:event_cbo_iniNameItemStateChanged
    
    //Action performed to save the item in the inventory table
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if((txt_iniId.getText()).equals("")) {    //Check to see if any item id is selected
            JOptionPane.showMessageDialog(null,"Please select the item to enter in the inventory");
        } else {
            String sql ="insert into inventory " 
                            + "(inDate, item_iId, iniName, inQty)"
                            + "values (?,?,?,?) ";
            try {
                pst = conn.prepareStatement(sql);
                
                DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                pst.setString(1,format.format(txt_inDate.getDate()));
                pst.setInt(2,Integer.parseInt(txt_iniId.getText()));
                pst.setString(3,cbo_iniName.getSelectedItem().toString());
                pst.setInt(4,Integer.parseInt(txt_inQty.getText()));
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Added");

            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }finally {
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e) {}
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed
    
    //Action performed when clear all button is clicked
    private void btn_clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearAllActionPerformed
        
        //Code to remove all selected items       
        txt_inDate.setDate(null);
        txt_iniId.setText("");
        cbo_iniName.setSelectedItem(0);
        txt_inQty.setText("");
    }//GEN-LAST:event_btn_clearAllActionPerformed

    //Action performed when only item details need to be cleared
    private void btn_clearitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearitemActionPerformed
        //Code to remove only item detailsdsfsdf
        txt_iniId.setText("");
        cbo_iniName.setSelectedItem(0);
        txt_inQty.setText("");
    }//GEN-LAST:event_btn_clearitemActionPerformed

    //Code to go back
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        inventory i = new inventory();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clearAll;
    private javax.swing.JButton btn_clearitem;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cbo_iniName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JPanel pnl_main;
    private org.jdesktop.swingx.JXDatePicker txt_inDate;
    private javax.swing.JTextField txt_inQty;
    private javax.swing.JTextField txt_iniId;
    // End of variables declaration//GEN-END:variables
}
