//Main menu of our software
package rohanbakery;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class mainMenu extends javax.swing.JFrame {

    //Constructor to initilaise components
    public mainMenu() {
        initComponents();
        centerFrame();  //Set frame in the center of the screen
    }
    
    //Functin to set frame in the center of the screen
    public void centerFrame() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation((size.width/2 - getWidth()/2),(size.height/2 - getHeight()/2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        lbl_billingMenu = new javax.swing.JLabel();
        lbl_billingMenu1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_inventoryRequirement = new javax.swing.JButton();
        btn_addUser = new javax.swing.JButton();
        btn_generateBill1 = new javax.swing.JButton();
        btn_inventoryDetails1 = new javax.swing.JButton();
        btn_itemDetails2 = new javax.swing.JButton();
        btn_generateSalesReport1 = new javax.swing.JButton();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main menu");
        setResizable(false);

        pnl_main.setLayout(null);

        lbl_billingMenu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_billingMenu.setText("Mangement menu");
        pnl_main.add(lbl_billingMenu);
        lbl_billingMenu.setBounds(440, 80, 160, 20);

        lbl_billingMenu1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbl_billingMenu1.setText("Billing menu");
        pnl_main.add(lbl_billingMenu1);
        lbl_billingMenu1.setBounds(130, 80, 130, 20);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/logout.png"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        pnl_main.add(btn_logout);
        btn_logout.setBounds(610, 20, 50, 30);

        btn_inventoryRequirement.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_inventoryRequirement.setText("Generate inventory requirement pdf");
        btn_inventoryRequirement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventoryRequirementActionPerformed(evt);
            }
        });
        pnl_main.add(btn_inventoryRequirement);
        btn_inventoryRequirement.setBounds(70, 350, 260, 40);

        btn_addUser.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_addUser.setText("Add user");
        btn_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addUserActionPerformed(evt);
            }
        });
        pnl_main.add(btn_addUser);
        btn_addUser.setBounds(380, 210, 260, 40);

        btn_generateBill1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_generateBill1.setText("Update item in Bill / Generate bill pdf");
        btn_generateBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateBill1ActionPerformed(evt);
            }
        });
        pnl_main.add(btn_generateBill1);
        btn_generateBill1.setBounds(70, 210, 260, 40);

        btn_inventoryDetails1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_inventoryDetails1.setText("Add / Delete item from inventory");
        btn_inventoryDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventoryDetails1ActionPerformed(evt);
            }
        });
        pnl_main.add(btn_inventoryDetails1);
        btn_inventoryDetails1.setBounds(70, 280, 260, 40);

        btn_itemDetails2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_itemDetails2.setText("Add / Delete / Update item details");
        btn_itemDetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_itemDetails2ActionPerformed(evt);
            }
        });
        pnl_main.add(btn_itemDetails2);
        btn_itemDetails2.setBounds(70, 140, 260, 40);

        btn_generateSalesReport1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_generateSalesReport1.setText("Generate sales report");
        btn_generateSalesReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateSalesReport1ActionPerformed(evt);
            }
        });
        pnl_main.add(btn_generateSalesReport1);
        btn_generateSalesReport1.setBounds(380, 140, 260, 40);

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/Background image.jpeg"))); // NOI18N
        pnl_main.add(lbl_background);
        lbl_background.setBounds(0, 0, 680, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Code for logout button
    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        login l = new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    //Code to open item list module
    private void btn_itemDetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_itemDetails2ActionPerformed
        itemList iL = new itemList();
        iL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_itemDetails2ActionPerformed

    //Code to open generate bill module
    private void btn_generateBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateBill1ActionPerformed
        generateBill gB = new generateBill();
        gB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_generateBill1ActionPerformed

    //Code to open inventory module
    private void btn_inventoryDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventoryDetails1ActionPerformed
        inventory i = new inventory();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_inventoryDetails1ActionPerformed

    //Code to open inventory requiement module
    private void btn_inventoryRequirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventoryRequirementActionPerformed
        //Code to be added for future growth of the project
        JOptionPane.showMessageDialog(null, "Functionality not available till now. Plese return later");
    }//GEN-LAST:event_btn_inventoryRequirementActionPerformed

    //Code to open sales and profit report module
    private void btn_generateSalesReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateSalesReport1ActionPerformed
        //Code incomple due to lack of time
        //Can be added to enhance the capabalities of the system
        JOptionPane.showMessageDialog(null,"Functionality not available till now. Plese return later");
    }//GEN-LAST:event_btn_generateSalesReport1ActionPerformed

    //Code to open add user module
    private void btn_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addUserActionPerformed
        //Code incomple due to lack of time
        //Can be added to enhance the capabalities of the system
        JOptionPane.showMessageDialog(null,"Functionality not available till now. Plese return later");
    }//GEN-LAST:event_btn_addUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addUser;
    private javax.swing.JButton btn_generateBill1;
    private javax.swing.JButton btn_generateSalesReport1;
    private javax.swing.JButton btn_inventoryDetails1;
    private javax.swing.JButton btn_inventoryRequirement;
    private javax.swing.JButton btn_itemDetails2;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_billingMenu;
    private javax.swing.JLabel lbl_billingMenu1;
    private javax.swing.JPanel pnl_main;
    // End of variables declaration//GEN-END:variables
}
