//Class for removing entire bill from the billing summary
package rohanbakery;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;


public class removeBill extends javax.swing.JFrame {

    //Global variables of the class
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    boolean listLoaded = false;
    
    //Constructor for initialist components
    public removeBill() {
        initComponents();
        centerFrame();  //Set frame in the center of the screen
        conn = ConnectToDatabase.getConnection();   //Get connection to the database
        setComboBoxValues();    //Set the combo box values
        listLoaded = true;  //List has been loaded completely
    }
    
    //Functin to set frame in the center of the screen
    public void centerFrame() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation((size.width/2 - getWidth()/2),(size.height/2 - getHeight()/2));
    }
    
    //Function to set the values of the combo box using the item id in the billing table
    public void setComboBoxValues() {
        String sql = "select bNumber from billing where bOk=? group by bNumber";
        
        cbo_bNumber.removeAllItems();
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1,"Yes");
            rs = pst.executeQuery();
            
            while (rs.next()) {
                cbo_bNumber.addItem(rs.getString(1));
            }
            
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null,"Billing list cannot be loaded");
        }finally {
            try{
                rs.close();
                pst.close();
                
            }catch(Exception e) {}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_bCustName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbo_bNumber = new javax.swing.JComboBox<>();
        btn_deleteBill = new javax.swing.JButton();
        txt_bDate = new org.jdesktop.swingx.JXDatePicker();
        btn_clea = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_bAmount = new javax.swing.JTextField();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove entire bill");
        setAlwaysOnTop(true);
        setResizable(false);

        pnl_main.setLayout(null);

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        pnl_main.add(btn_back);
        btn_back.setBounds(260, 10, 100, 30);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Remove  entire bill :");
        pnl_main.add(jLabel1);
        jLabel1.setBounds(30, 10, 230, 23);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Bill date : ");
        pnl_main.add(jLabel3);
        jLabel3.setBounds(40, 110, 110, 16);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Customer name : ");
        pnl_main.add(jLabel4);
        jLabel4.setBounds(40, 160, 110, 16);

        txt_bCustName.setEditable(false);
        txt_bCustName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_bCustName);
        txt_bCustName.setBounds(150, 150, 210, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Select Bill number : ");
        pnl_main.add(jLabel6);
        jLabel6.setBounds(40, 60, 110, 16);

        cbo_bNumber.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbo_bNumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_bNumberItemStateChanged(evt);
            }
        });
        pnl_main.add(cbo_bNumber);
        cbo_bNumber.setBounds(150, 50, 210, 30);

        btn_deleteBill.setText("Delete bill");
        btn_deleteBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteBillActionPerformed(evt);
            }
        });
        pnl_main.add(btn_deleteBill);
        btn_deleteBill.setBounds(40, 270, 130, 40);

        txt_bDate.setEditable(false);
        pnl_main.add(txt_bDate);
        txt_bDate.setBounds(150, 100, 210, 30);

        btn_clea.setText("Clear");
        btn_clea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cleaActionPerformed(evt);
            }
        });
        pnl_main.add(btn_clea);
        btn_clea.setBounds(210, 270, 130, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Bill Amount : ");
        pnl_main.add(jLabel5);
        jLabel5.setBounds(40, 210, 110, 16);

        txt_bAmount.setEditable(false);
        txt_bAmount.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnl_main.add(txt_bAmount);
        txt_bAmount.setBounds(150, 200, 210, 30);

        lbl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.images/Background image.jpeg"))); // NOI18N
        pnl_main.add(lbl_background);
        lbl_background.setBounds(0, 0, 430, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    //Action performed to delete the bill
    private void btn_deleteBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteBillActionPerformed
        if((cbo_bNumber.getSelectedItem().toString()).equals("")) {    //Check to see if bill details has been selected
            JOptionPane.showMessageDialog(null,"Please select the bill number to delete");
        } else {
            String sql ="update billing set bOk=? where bNumber=?"; 
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1,"No");
                pst.setString(2,cbo_bNumber.getSelectedItem().toString());
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Bill removed");
                
                //Reset combo box values
                listLoaded = false;
                setComboBoxValues();    //Set the combo box values
                listLoaded = true;  //List has been loaded completely
                
                

            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }finally {
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e) {}
            }
        }
    }//GEN-LAST:event_btn_deleteBillActionPerformed
    
    //Action performed when clear button is clicked
    private void btn_cleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cleaActionPerformed
        
        //Code to remove all selected bill details        
        txt_bDate.setDate(null);
        txt_bCustName.setText("");
        txt_bAmount.setText("");
    }//GEN-LAST:event_btn_cleaActionPerformed

    //Action performed to show the details of the bill when bill number is selected
    private void cbo_bNumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_bNumberItemStateChanged
        if(listLoaded) {
            String sql = "select bNumber, bDate, bCustName, sum(bAmount) from billing where bNumber=? group by bnumber";
        
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1,cbo_bNumber.getSelectedItem().toString());
                rs = pst.executeQuery();
                rs.next();  //Move resultset to the first pointer
                       
                txt_bDate.setDate(rs.getDate(2));
                txt_bCustName.setText(rs.getString(3));
                txt_bAmount.setText(rs.getString(4));

            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Billing details cannot be found");
            }finally {
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e) {}
            }
        }
    }//GEN-LAST:event_cbo_bNumberItemStateChanged

    //Code to go back
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        generateBill gb = new generateBill();
        gb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(removeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(removeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(removeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(removeBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new removeBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clea;
    private javax.swing.JButton btn_deleteBill;
    private javax.swing.JComboBox<String> cbo_bNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_background;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JTextField txt_bAmount;
    private javax.swing.JTextField txt_bCustName;
    private org.jdesktop.swingx.JXDatePicker txt_bDate;
    // End of variables declaration//GEN-END:variables
}
